### ISSUE TITLE
No package available for Apple Silicon Macs

### ISSUE THREAD

**Issue by kokroo** [tweedge/unishox2-py3#6]
There is no installable package available for Apple Silicon Macs on PyPI.

I believe the fix for this should be quite simple. Thanks!

**Comment by tweedge** [comment]
Hi! I've added an arm64 MacOS build job in the CI, which is building for Python 3.8, 3.9, and 3.10.

I believe this should now be working but please let me know if you have any trouble with it! Unfortunately I don't have an Apple Silicon Mac to confirm myself.

**Comment by tweedge** [comment]
Going to assume all is well, please reopen if there are any problems with the arm64 distribution of unishox2-py3! Happy to dig into it. Have a good one! ^_^
